# Generated by Django 4.1.2 on 2022-10-10 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('job_no', models.AutoField(primary_key=True, serialize=False)),
                ('po_code', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('po_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=256)),
                ('addendum', models.IntegerField(default=0)),
                ('modified_date', models.DateField(auto_now=True)),
                ('revision', models.CharField(default='A', max_length=32)),
                ('is_validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BBURow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_line_item_no', models.IntegerField()),
                ('po_position_no', models.IntegerField()),
                ('erection_item', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('drawing', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('supplier_identification_no', models.TextField(blank=True, default='', null=True)),
                ('revision', models.CharField(default='A', max_length=32)),
                ('comment', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('uom', models.CharField(default='P', max_length=256)),
                ('bbu_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(auto_now=True)),
                ('forecast_date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbu.project')),
            ],
        ),
    ]
