# Generated by Django 4.1.2 on 2022-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='revision',
            field=models.CharField(default='A', max_length=32),
        ),
    ]
