# Generated by Django 4.1.2 on 2022-10-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbu', '0002_alter_project_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='addendum',
            field=models.IntegerField(default=0),
        ),
    ]
