# Generated by Django 4.1.2 on 2022-10-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbu', '0004_bburow_forecast_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bburow',
            name='comment',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bburow',
            name='drawing',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bburow',
            name='revision',
            field=models.CharField(default='A', max_length=32),
        ),
        migrations.AlterField(
            model_name='bburow',
            name='bbu_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bburow',
            name='forecast_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bburow',
            name='supplier_identification_no',
            field=models.TextField(null=True),
        ),
    ]
