# Generated by Django 4.1.2 on 2022-10-10 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbu', '0005_bburow_comment_bburow_drawing_bburow_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bburow',
            name='comment',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='bburow',
            name='drawing',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='bburow',
            name='forecast_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bburow',
            name='supplier_identification_no',
            field=models.TextField(default=''),
        ),
    ]
