# Generated by Django 4.1.2 on 2022-10-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbu', '0007_bburow_modified_timestamp_alter_bburow_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bburow',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bburow',
            name='drawing',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bburow',
            name='supplier_identification_no',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
